sync:
    build: .
    command: python naive.py
    environment:
        - DEBUG
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./naive.py:/naive.py
async:
    build: .
    command: python async.py
    environment:
        - DEBUG
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./async.py:/async.py
test:
    build: .
    command: date
